#!/usr/bin/perl

use strict;

open(F, "<CHANGES")||die "Unable to open changelog: $!";
my @lines=<F>;
close(F);

$lines[0]=~s/(\d.*?:)\s*\n/$1 @{[`date +%Y%m%d`]}/s
  if ($lines[0]=~/(\d.*?):\s*\n/s);

my $lines=join('', @lines);

$lines=~s/\t/  * /g;
$lines=~s/(\d.*?): (\d*)(.*?\n\n)/aardmail ($1) unstable; urgency=low\n$3\n -- Bernd Wachter <bwachter\@lart.info>  @{[`date -R -d $2`]}\n\n/gs;

open(F, ">debian/changelog")||die "Unable to open changelog: $!";
print F $lines;
close(F);
