.TH "_addrlist" 3 "Sun Aug 7 2011" "aardmail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_addrlist \- 
.PP
A structure to store a list of email addresses.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <addrlist.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBaddress\fP [AM_MAXUSER]"
.br
.RI "\fIAn email address. \fP"
.ti -1c
.RI "int \fBaccepted\fP"
.br
.RI "\fIFlag for processing notes, currently unused. \fP"
.ti -1c
.RI "\fBaddrlist\fP * \fBnext\fP"
.br
.RI "\fIPointer to the next entry. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A structure to store a list of email addresses. 
.PP
Definition at line 23 of file addrlist.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for aardmail from the source code.
