.TH "aardmail-pop3c" 1 "June 4, 2005"
.SH NAME
aardmail \- a collection of programs useful for handling mail
.SH "DESCRIPTION"
.PP
\fBaardmail\fR is a package with useful tools for different kinds of mailhandling.
.SH "SEE ALSO"
.PP
aardmail-miniclient (1), aardmail-pop3c (1).
.SH "AUTHOR"
.PP
aardmail was written by Bernd 'Aard' Wachter <bwachter@lart\&.info>. It can be obtained at \fIhttp://bwachter.lart.info/projects/aardmail/\fP
